.TH SABRE 6 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
sabre \- SVGAlib fighter plane simulator
.SH SYNOPSIS
.B sabre
.br
.B RunSabre
.SH "DESCRIPTION"
Unfortunately, there is no standard documentation for the
.BR sabre
and
.B RunSabre
programs.
However there is some online documentation, just run
.BR RunSabre .
See also files in the
.I /usr/share/doc/sabre
directory.
.SH AUTHOR
This manual page was written by Milan Zamazal <pdm@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
